# Hizkuntzak eta Edukiak Batera Ikastea (CLIL-HEBI)

Hizkuntzak eta Edukiak Batera Ikastea - Content and Language Integrated Learning - Aprendizaje Integrado de Contenido y Lenguas Extranjeras

Baliabide nagusiak: [@coyleContentLanguageIntegrated2012; @hezkuntzasaila772023DEKRETUA2023; @euskojaurlaritzaHezkuntzaMarkoHirueledunaren2011; @europakokontseiluaHizkuntzenEuropakoErreferentzia2022] [\*](../diapoak/06-CLIL-ta.html)

Zer aztertuko dugun

-   Zer da CLIL?
-   Zergatik da garrantzitsua?
-   Zer eragin du CLILi garrantzia ematean?
-   Nola ulertu behar da CLIL beste batzuen aurrean? Zein da gai honen helburua?
-   Zer eragin du gai honen garapenean?
-   Zein da gai honen inguruko literaturaren ikuspegi nagusia?
-   Zer aldatu beharko litzateke CLIL hobeto ulertzeko?
-   Zein da gai honen inguruko ikerketa gehien zabaltzen duen ikuspegi edo teoria?
-   Zer da gai honen inguruko azken ikerketen ondorio nagusia?

------------------------------------------------------------------------

## Nondik nora?

Kontu batzuk horrelako planteamendu pedagogikoaren oinarrian ditugu:

-   Mundu globalizatua, mugikortasun handia harremanak oso ugari hizkuntzak garrantzi handia
-   Europako Kontseiluak eleaniztasunaren aldeko jarrera: 1+2
-   EHn testuinguru soziolinguistikoa: bi hizkuntza ofizialak gehi (mundu mailako) lingua franca(k?)
-   Eskolaren emaitzak hobetu nahi
-   Planteamendu berriak atzerriko hizkuntzan hobeto jarduteko:
    -   Hizkuntzen trataera bateratua
    -   CLIL/HEBI/AICLE

Hizkuntza eta Edukiak Batera Ikastea (CLIL: Content and Language Integrated Learning).

Europan indartzen da 1990eko hamarrurtekoan (http://www.clilcompendium.com/miles.htm)

Euskal Herrian, murgiltze programetan badugu eskarmentua\
Murgiltze programa: HEBIren aldaera bat?

Orain, 3 hizkuntzarekin ideia bera garatu

Hizkuntza eta Edukiak Batera Ikastea (CLIL: Content and Language Integrated Learning).

## Zer egiten da?

"Beste" hizkuntza erabili (zerbait) ikasteko, eta (zerbait) ikasi "beste" hizkuntza erabiltzeko

> The main principle in CLIL: use language to learn and learn to use language.

Hizkuntza eta edukiak batera ikastea. Biei jartzen zaie arreta. Bietan helburuak lortu nahi dira. Edukiei garrantzi handia.

Helburu linguistikoa da ikasleak maila hobetzea hizkuntza-komunikaziorako gaitasunean

Beste helburua da curriculumeko bestelako edukiak ikastea (konpetentziak garatzea)

### Oinarriko ideia batzuk:

#### CLIL compedium

iturria: <http://www.clilcompendium.com/brief.htm>)

-   Umeak eta gazteak oso onak izaten dira hizkuntzak ikasten hizkuntza horiek etxean erabiltzen direnean, eta horrengatik pentsatu ohi da txikitan ikasten direla errazenik eta hobekienik hizkuntzak
-   Adin handiagokoek gehienean hizkuntza-eskoletan ikasten dituzte hizkuntzak
-   Hizkuntza-ikasketan arrakasta izaten da jendeak irakaskuntza jasotzen duenean egiazko bizitzako egoerak baliatuta hizkuntza ikasteko
-   Hizkuntza erabiltzea egiazko komunikatu-beharrak asetzeko (eskolan, eskolako lanak egiteko)
-   Hizkuntza jasotzeko gaitasun handia esplikatzeko arrazoi bat da ikaste-inguruaren naturaltasuna
-   CLILek (HEBIk) eskaini nahi du ahalik eta egoerarik naturalena, ikasleen motibazioa handitzeko eta hizkuntzak ikastearen aurrean jarrera positiboak indartzeko

#### Coyle (2010):

-   Garrantzia handia ematen zaio irakaslearen jarrera ohartuari. Irakasleak berak egin eta probatu behar du hurbiltze modu hau.
-   CLIL ez da hizkuntza eta edukiak batera jartzea, besterik gabe: bi alderdiak zaindu behar dira. Bietan helburuak ezarri behar dira. Bien aitzinamendua programatu behar da.
-   CLIL ez da "beste hizkuntza batean ikastea", besterik gabe; beste hizkuntza batean ikaste oro ez da CLIL planteamendu bat.
-   Adibidez, atzerriko unibertsitate batean eskolak hartzea, berez CLIL da?
-   Hizkuntza-helburuak eta beste edukien helburuak zaindu behar dira.
-   CLIL beste hurbiltze modu bat da, gauzak egiteko beste ikuspegi bat.
-   CLIL ezartzeko, ez da modu bakar bat. Testuinguruak desberdinak dira eta bakoitzaren ezaugarriak analizatu behar dira. CLIL malgua da, testuinguru desberdinetan egokitu daiteke. (Coyle, 2010)

##### "4C markoa": Content, Communication, Cognition, Culture

-   Edukia (content): eduki berrietan progresioa: jakintzetan, trebetasunetan, ulerkuntzan (ez bakarrik esan-edukietan, jakintza soilean)
-   Komunikazioa (communication): Interakzioa, aitzinamendua hizkuntzaren erabileran eta ikasketan. Learning to use language and using language to learn.
    -   Hizkuntza erabili egiteari garrantzi handia (eta ez horrenbeste gramatikaren araberako antolamendua)
-   Kognizioa (cognition): Goi-mailako gaitasunak lantzeko ideia: arazoak ebaztea, desafioak onartzea eta haietaz gogoeta egitea.
    -   "Desafio" giroa, zailtasunak gainditzeko gogoa
    -   Ez da irakasleak ikasleari jakintza transmititzea eta bai ikasleak bere jakintza eraikitzea
-   Kultura (culture): beste kultura batekin harremana
    -   Beste hizkuntza batean ikastean besteak ulertzeko gaitasuna lantzen da, nazioartekotasunaz ohartzeko ona
    -   Egiazko materiala erabiltzean, besteen kulturaz ohartzen gara, eta ondorioz geure burua ere hobeki ezagutzen dugu
    -   Ingurugiroan, hizkuntza-aniztasuna eta kultura-aniztasuna. (Coyle 2010: 53 eta hurr.)

Content, Communication, Cognition, Culture - Edukia, komunikazioa, kognizioa, kultura: laurak lotuta

**Edukiak** "tiratzen du" lehenbiziko (besteetan ere aurrera egiteko).

Hizkuntza-gaitasunean hobera egin behar da, "**eskatu**" egin behar da, ez egoteko beti lehengo tokian

HEBIn batera bildu behar dira edukiak eta hizkuntza **kognizio** mailan eta kultura mailan

HEBIn arretaz zaindu behar dira aitzinamenduak lau ataletan: edukia, komunikazioa, kognizioa, kultura

#### Langé, Gisella 2001

##### Definizioa eta

-   Hizkuntza bera ez beste eduki bat irakastea beste "atzerriko" hizkuntza baten bidez.
-   Oreka bilatzen da edukien eta hizkuntzaren ikastearen artean.
-   Hizkuntzaz besteko edukiak 2Hren bidez garatzen dira eta 2H garatzen da edukia lantzearen bidez.
-   HEBI hainbat modutan egin daiteke: urte batez gai bat edo gehiago irakats daiteke horrela, ikasgai bat edo gehiago, moduluren bat, proiekturen bat, ikasturtearen zati bat...

##### Kontuan hartzeko ideia batzuk

-   Esposizioaren zenbatekoa
-   Esposizioaren nolakoa, kalitatea
-   Ikasteko motibazioa

###### Esposizioaren zenbatekoa

-   Bigarren (edo "beste") hizkuntza bat ikasteko faktore oinarrizko bat da esposizioa.
-   Ikasleek hizketa espontaneoarekin, "naturalarekin" harremana izan behar lukete.
-   Hobe testuinguru interaktibo batean baldin bada, non informazio asko jaso daitekeen beste hizkuntzaren estrukturaz eta funtzionamenduaz. Ikasleak horrelakoetan hipotesiak ere egiten ditu, ikasten ari den hizkuntzaz.
-   Ikasteko prozesua luzea izan ohi da. Ikasleak hizkuntzaren jakite "okerrak" izanen ditu hizkuntza horren alderdi ugariak beretu arte. HEBIk aukera ematen du esposizio denbora handitzeko.

###### Esposizioaren nolakoa, kalitatea

-   HEBIk, esposizio denbora gehiago ez ezik, kalitate handiagoko esposizioa eskaintzen du.
-   HEBIko eskoletan oso kontuan hartzen da interakzioa, estilo hori da nagusi. Ikasleek aukera ona behar dute irakaslearekin eta ikaskideekin harremana izateko. Horrela ikasleek praktikatzen dute dakitena eta "behartuta" daude beren hizkuntza baliabideak "handitzera", edukia ikasteak dakartzan eskakizunei aurre egiteko.
-   Gainera, atzerriko hizkuntza (edo "gainerako" hizkuntza, "beste hizkuntza") erabiltzen denez eduki ez linguistikoak jasotzeko, horrek eskatzen du sakonagoko prozesamendua, eta azkenean hizkuntzaren "ikaste hobetua" lortzen da.
-   HEBIan sarritan arazoak konpondu behar izaten dira hizkuntza erabilita. Ikasleak erabiltzen duelarik ikasten ari den hizkuntza bat zertarako-eta hizkuntza bera ez den beste ikasgai baten edukia ulertzeko eta ikasteko, beste kognizio prozesu batzuk abiatzen dira 2Hn (lehen hizkuntzaren ikastean gertatzen den gauza bera).

##### Ikasteko motibazioa

-   HEBIk bilatzen du motibazio intrinsekoa, barne-motibazioa
-   Ikaslea ari da hizkuntza erabiltzen zeregin interesgarri eta esanguratsuetan
-   Hau da: HEBIk aukera anitz eskaintzen ditu *zeharbidezko hizkuntz ikasketa*[^06-hebi-1] gertatzeko
    -   Ikaslearen arreta beste zerbaiti begira dagoenean, orduan gertatzen da ikasketa sakona, eta luze irauten duena
    -   Positiboki osatzen du berariazko hizkuntza ikasketa (ohiko hizkuntz eskola emanaldietan gertatu ohi dena)

[^06-hebi-1]: Zeharbidezko hizkuntz ikasketa, bidenabarreko hizkuntz ikasketa, ikasketa intzidentala = incidental learning.<br> Ikus zer esan nahi duen termino horrek, beste dokumentu batean ("Incidental learning dela eta")

##### Zer diziplinatan, ikasgaitan?

###### Hausnarbiderako

-   Edozein gai irakats daiteke atzerriko hizkuntzaren bidez, baina gaiek ezaugarri desberdinak dituzte
-   Batzuetan hizkuntzak berak pisu handia du: historia, filosofia, politika...
-   Beste batzuetan berbaz besteko komunikazioak pisu handiagoa izan dezake (material grafikoak, ikustekoak...): heziketa fisikoa, geografia, ...
    -   Mapa baten laguntzarekin erraz landu daitezke honelako esapideak: "Rome is the capital city of Italy" edo "The capital of Italy is Rome".
    -   Heziketa fisikoko irakasleak erakuts ditzake zuzenean mugimendu modu batzuk eta haiei dagozkien aditzak irakatsi: running, jumping, turning round, climbing.
-   Kontu handiarekin sartu behar dira ikasgai berriak: testuinguruaren esanguratsutasunari arreta jarri behar zaio eta zuzen ulertzen dela bermatzen saiatu (ikasi-behar berria ongi aurkeztu, haren ulertze zuzena bermatzeko).

###### Denetarako hizkuntza eta berariazkoa

-   Ikasgai guztiek badute orotariko hizkuntzaren oinarriaren beharra eskolako ohiko jardunetarako.
-   Giza-zientzien eta ikasgai zientifiko eta teknikoen artean desberdindu daiteke?
-   Giza-zientzietako hizkuntza, oro har, hizkuntza arruntetik "hurbilago" dago (egunkarietan, komunikabideetan entzun daiteke, elkarrizketetan...). **Ados?**
-   Hizkuntza tekniko-zientifikoan, berriz, alor horretan besterik entzuten ez diren hitz asko ageri da, eta egitura sintaktiko bereziagoak ere bai

**Alderatu historiako eta kimikako hiztegiak. Nazioarteko hitz asko?**

###### Zer hizkuntzatan egin HEBI

Erabakitzeko litezkeen irizpide batzuk:

-   Hurbiltasun geografikoa, antolamendu politikoa, ...: frantsesa, espainola...
-   Behar ote dugu lingua franca bat gure harremanetarako gaitasuna zabaltzeko? Zein? Ingelesa? Txinera? Gaztelania? Frantsesa?
-   Europako Kontseiluak zer dio? 1+2 planteamendua gomendatzen du (ez bakarrik ingelesa)

Hizkuntzen arteko antz-aldeak:

-   Euskararen kasuan, aski desberdina da inguruko hizkuntza guztietatik Gaztelaniak eta frantsesak badituzte antzak
-   Alemanak?

**Euskal Herrian zeren arabera erabakitzen da?**

###### Ikasleei begira

-   HEBIk ez du izan nahi hezkuntza elitista; edozein ikaslek har dezake onura HEBItik
-   Ikasleek eta gurasoek libreki hautatuta, hobe
-   Ikastetxe bakoitzak erabaki nola osatu taldeak, nola hautatu ikasleak, zer hizkuntz (eta bestelako) eskakizun ezarri sartzeko

Ikasleentzako onurak:

-   Motibazioa hazi ohi da, eduki interesgarriagoak eta autentikoagoak baliatu ohi direlako (*benetako materialaren* aurreko esposizioa)
-   Interakzio handiagoak eta lankidetzarako joerak auto-konfiantza eta auto-estimua zabaltzen du; ikasle independenteagoak eta lana antolatzeko gaitasunak gehiago garatzeko bidea
-   Hizkuntza gehigarrian esposizio denbora handiagoak hizkuntza-konpetentzia sendotzen du
-   Ikasteko baldintza aldekoagoak izanik, HEBIk laguntzen du **ikasten ikasteko** gaitasuna garatzen
-   Edukiak eta hizkuntza bateratzean, eta ikasleak ari direlarik akademikoki eta kognitiboki eskakizun handiagokoak diren jardunetan, HEBIk bizitu egiten ditu sormenezko pentsamendu prozesuak; aukera hobeak izaten dira konstruktibismoaren eta ikasketa kooperatiboa bezalako orientabideak modu autentikoagoan integratzeko eta aplikatzeko
-   HEBIk aukera eman nahi du komunikazioa hobetzeko pertsonen eta kulturen artean. Hizkuntza gehigarriarekin izaten den kontaktuak eta haren ikasketan jasotzen den ikuspegiak laguntzen du garatzen komunikazio konpetentzia beste hizkuntza batean, eta gainera hizkuntzak ikasteko eta irakasteko beste ikuspegi bat eskaintzen du

###### Irakasleei begira

Biziki gomendaturiko ezaugarriak HEBIko irakasle izateko[^06-hebi-2]

[^06-hebi-2]: ea zer iduritzen zaizkigun

-   Ongi erabiltzea hizkuntza gehigarria, beste hizkuntza.
-   Ikasleen lehen hizkuntza jakitea ere onuragarria da (irakasleek igar lezake non izan daitezkeen ikasteko eragozpenak).
-   HEBIko irakasleak aditua izan beharko luke edukiaren jakintza-alorrean eta gainera jakintza beharko luke *beste* hizkuntza bat ikastean parte diren osagai kognitibo, soziokultural eta psikologikoez.
-   On litzateke HEBIko irakasleak lan-taldean aritzeko gaitasunak garatzea (eduki-irakasleen eta hizkuntza-adituen arteko lankidetza). Lankidetza-giro on batek hagitz handitu eginen du ikaslearen ikastea.
-   HEBIko irakasleak prest egon behar luke ikasgelan ikerketan aritzeko. Garrantzi handikoak dira, orobat, luzera begirako konpromisoa, edukian eta hizkuntzan prestakuntza bikoitza, edo behinik behin, interesa eta trebetasuna edukia eta hizkuntza bateratzeko, eta halaber metodologia interaktiboak baliatzeko gaitasuna.

Onurak irakasleentzat:

-   Elkarrekin lan eginez, eduki-irakasleek eta hizkuntza-irakasleek konpartitu dezakete beren norbanako-jakintza eta eraiki dezakete elkar-jakintza.
-   Garapen profesionala izateko aukerarik?

### Eta Euskal Herrian? Hezkuntza Marko Hirueleduna

Euskal Herriaren desafioa: 3. (edota 4.) hizkuntza ikas-irakastea ikuspegi honetatik

1996an hasi

2003: Hezkuntza marko hirueleduna (HMH)

Gaur egun: hainbat ikastetxe proiektuan sartuak (esperimentazioan)

### 3.CLIL/EHII metodologia (Content and Language Integrated Learning / Edukien eta Hizkuntzen Ikaskuntza Integratua)

> Hezkuntza Marko Hirueledunaren saiakuntza-proposamenaren helburua da Euskadiko ikasleek hizkuntza-komunikazioko gaitasuna nabarmen hobetzea curriculumeko hizkuntza guztietan, oro har. Horretarako, hizkuntzak curriculum-edukien bidez irakastea sustatzen du, komunikazio-metodologia batean oinarrituta, eta alde batera uzten du hizkuntza jakingai gisa ikastearen kontzeptu tradizional eta gramatikala; izan ere, kontzeptu tradizional horrek ikasteko proposatzen dituen jarduerak askotan testuinguru irreal eta ez oso garrantzitsuetakoak izaten dira.
>
> CLIL (Content and Language Integrated Learning) metodologia-ikuspegi bat da, eta curriculum-edukiak eta hizkuntzak era bateratuan irakatsi behar direla hartzen du onarritzat. Irakasteko hizkuntza ikaslearen H1ekin bat ez datorren testuinguru guztietan aplikatzen da ikuspegi hori. Metodologiaren ezaugarri nagusia da edukiaren eta hizkuntzaren ikuspegi duala gehitzen duela, eta bi alderdiak batera lantzen dituela; curriculum-edukiari edo hizkuntzari emango zaio garrantzia, jarritako helburuaren edo proposatutako zereginaren arabera.
>
> Gaur egungo gizarte-aldaketek atzerriko hizkuntzak jakitea eta era eraginkorrean erabiltzea eskatzen dute; hizkuntza horiek ikasteko erarik eraginkorrena zein den hausnartzera bultzatu gaitu horrek. Alde horretatik, ikusi dugu hizkuntzak irakasteko metodologia aldatu beharra dagoela: bilakaera bat egon da, eta nagusiki formala eta estrukturala zen irakaskuntzatik ikaskuntzaren helburu nagusitzat hizkuntza erabiltzea duen irakaskuntzara pasatu gara. Irakaskuntza berri horrek garrantzi handiagoa ematen dio hizkuntza-erabileren komunikazio-funtzioari, hizkuntza-unitateen formari baino. XXI. mendeko ikasleek hizkuntzak erabiltzeko gai izan behar dute. Gainera, hizkuntzak irakasteko eta ikasteko prozesuak lantzen dituzten zientzietan egon diren aurrerapenek egiaztatu dute eraginkorragoa dela eginez ikastea (learn by doing) eta hizkuntza aldi berean ikastea eta erabiltzea (learn as you use and use as you learn). Horregatik, honako hau da CLIL ikuspegiaren goiburua: erabili hizkuntza ikasteko, eta ikasi hizkuntza erabiltzen (use language to learn and learn to use language).
>
> Hainbat ikerketak ondorioztatu dute CLIL ikuspegiak hizkuntza-komunikazioan gaitasun egokia eskuratzeko eta garatzeko balio izateaz gain, hizkuntzak irakastearekin eta ikastearekin lotutako beste alderdi batzuk ere sustatzen dituela. Hona hemen azpimarragarrienak
>
> -   Beste kultura batzuk ezagutzea eta errespetatzea.
> -   Eleaniztasunarekiko eta hizkuntzak ikastearekiko jarrera positiboa eta interesa piztea.
> -   Ikaslearentzako garrantzitsuak diren testuinguruetan erabiltzea hizkuntza.
> -   Trebetasun kognitiboak eta hizkuntza-trebetasunak gehiago garatzea.
> -   Hainbat estrategia didaktiko erabiltzea hizkuntzak irakasteko eta ikasteko.
> -   Ikasleak motibazioa eta bere buruan konfiantza izatea hizkuntza nahiz ikasgaia ikasteko.
>
> Beraz, CLIL ikuspegiak metodologia eguneratzeko aukera ematen die bai hizkuntza-irakasleei bai curriculumeko beste arlo batzuetako irakasleei. Izan ere, CLILen, irakaskuntzako profesional guztiak hizkuntza-irakasleak dira; batzuek hizkuntzak irakasten dituzte, eta besteek edukiak, baina guztiek metodologia integratzaile bat aplikatzen dute, eta metodologia horrek bermatzen du hizkuntza-helburuak, curriculum-arloetako edukiak eta trebetasun kognitiboak lotuta eta bat eginda egongo direla irakasteko eta ikasteko prozesuan.

#### Eleaniztasunaren oinarri teorikoak

-   Eleaniztunak hizkuntza-errepertorioa handitzen du, hiru hizkuntzatan
-   Besteen kulturak errepetatzeko joera handitzen da
-   Denak izan gaitezke eleaniztun
-   Maila desberdinetan garatzen ditugu gaitasunak, beharrizanen arabera
-   Eleaniztunak gaitasun berezia garatzen du, ez da elebakar batzuen batura
-   Kulturaniztasunaren osagaia

#### CLIL planteamenduaren arabera:

-   Denbora gehiago ematen da atzerriko hizkuntzaren eraginpean (esposizio handiagoa)
-   Hizkuntza bat beste edukiak ikasteko tresna gisa hartzen bada, beste gaitasun-alderdi batzuk aktibatzen dira
-   Eleaniztasunak kontzientzia metalinguistikoa (hizkuntz-oharmena) areagotzen du
-   Baldintzak egokiak badira, elebitasunak ahalmen kognitiboa handitzen du
-   Azpian dagoen gaitasun erkidea dela eta, errazagoa da bestelako hizkuntza-errepertorioak gehitzea
-   Ikasteko zereginekiko jarrera positiboak indartzen dira

#### Abantailak

-   Beste kultura batzuk ezagutzen dira eta haiek errespetatzeko joera indartzen da
-   Eleaniztasunarekiko jarrera positiboa eta interesa garatzen da
-   Ikaslearentzat garrantzitsuak diren testuinguruetan erabiltzen da ikasgai den beste hizkuntza
-   Trebetasun kognitiboak eta hizkuntza-trebetasunak gehiago garatzen dira
-   Hainbat estrategia erabiltzen dira hizkuntzak ikasteko eta irakasteko (ikasteko gaitasuna handituz)
-   Ikaslearen konfiantza hazten da bai hizkuntzarekiko eta bai ikas-edukiarekiko

#### Ikas-materialak:

Eusko Jaurlaritza:

-   INEBI: http://nagusia.berritzeguneak.net/hizkuntzak/inebi-1-1.php
-   BHINEBI: http://nagusia.berritzeguneak.net/hizkuntzak/bhinebi-2.php

Andaluziako Gobernua:

-   http://www.juntadeandalucia.es/educacion/descargasrecursos/aicle/html/pdf/004.pdf
-   http://www.juntadeandalucia.es/educacion/webportal/web/aicle/contenidos/

#### CLILeko oinarrizko hiztegiko batzuk

Hizkuntza gehigarria (Additional Language)\
: Gero eta gehiago erabiltzen da beste hitz batzuen ordez (atzerriko hizkuntza, bigarren hizkuntza, gutxiengo-hizkuntza), lehen hizkuntza ez den beste edozein hizkuntzari erreferentzia egiteko.

Ingurune elebiduna (Bilingual Environment)\
: Bi hizkuntza erabiltzen diren ingurunea

Esposizioa (Exposure)\
: Ikasle batek urte akademiko batean jasotzen duen HEBI-CLIL esperientziaren proportzioa

Apala/Txikia (Low)\
: eskola-denboraren %5-15 (teaching time)

Tartekoa (Medium)\
: eskola-denboraren %15-50

Handia (High)\
: eskola-denboraren % 50 baino gehiago (Euskal Herriko D eredu batzuk)

Atzerriko hizkuntza (Foreign Language)\
: Normalean ingurune sozialean erabili ohi ez den hizkuntza bat.

Murgiltze metodoa (Immersion Method)\
: HEBI-CLIL modu bat, bigarren hizkuntza batean esposizio handia izan ohi duena (ikasleen lehen hizkuntza gaztelania duen D eredu asko)

Jakintza eta ulerkuntza kulturartekoa/Kulturartekotasuna (Intercultural Knowledge & Understanding)\
: Nork bere kultura ulertzea beste kultura batzuekin harremanetan

Hizkuntza-oharmena (Language Awareness)\
: Hizkuntzen arteko antz-aldeez ohartzeko erraztasuna, sentsibilitatea

Gehiengo-hizkuntza (Majority Language)\
: Inguruneko jendartean erabiltzen den hizkuntza handiena, indartsuena.

Gutxiengo-hizkuntza (Minority Language)\
: Inguruneko jendartean gutxiengoak erabiltzen duen hizkuntza

Ingurune elebakarra (Monolingual Environment)\
: Ingurune bat non hizkuntza bat bakarra erabili ohi den nagusiki

Ama-hizkuntza (Mother Tongue)\
: Gehienean, ume batek ikasten eta erabiltzen duen lehen hizkuntzari esaten zaio hala, baina batzuetan umea elebidun osoa da eta beharbada bi hizkuntza (edo gehiago) izan ditzake lehen hizkuntzatzat

Ingurune eleaniztuna/Eleaniztun ingurunea/Eleanitzeko ingurunea (Multilingual Environment)\
: Ingurune bat non hiru hizkuntza edo gehiago egiazki erabiltzen diren

Jatorrizko hiztuna/hiztun natiboa (Native Speaker)\
: Helburu-hizkuntza (CLILen landu-gai den hizkuntza) bere lehen hizkuntzatzat duen pertsona

Jarrera eleaniztunak (Plurilingual Attitudes)\
: Jarrera hori dutenek balioa ematen diote hiru hizkuntza edo gehiago maila batean edo bestean erabiltzeko gaitasunari

Bigarren hizkuntza (Second Language)\
: Termino hori erabiltzen da deskribatzeko hizkuntza bat ingurunean ugari erabiltzen dena eta atzerriko hizkuntzatzat hartzen ez dena

Xede-hizkuntza (Target Language)\
: HEBI-CLILerako erabiltzen den hizkuntza

Trans-languaging\
: Hizkuntza bat baino gehiago erabiltzen denean HEBI-CLILeko ikasgela-lanetan

Gehiago jakiteko: http://www.clilcompendium.com/keyt.htm
