# Hizkuntzen Ikaskuntza Irakaskuntza eta Ebaluaziorako Europako Erreferentzia Markoa eta *Hizkuntzen Portfolio Europarra*

Baliabideak: [@europakokontseiluaHizkuntzenIkaskuntzaIrakaskuntza2005; @europakokontseiluaCommonEuropeanFramework2020; @davisHizkuntzenPortfolioEuroparra2004; @alariotriguerosPortfolioEuropeoLenguas2004]

Saio honetan, Europako hizkuntza politikaren oinarriak aztertzen dira. Ikasleek hizkuntza mailak eta hizkuntza portfolioa ulertzeko tresnak hartuko dituzte, eta beraien hizkuntza ibilbidea aztertzeko aukera izango dute.

## Klasekoak

Bereziki, saiatu behar dugu ulertzen zer ari garen esaten *A1*, *B2* edo *C1* esaten dugunean. Jakin badakigu ez dena berdin hogeita bi urteko irakaslegai baten komunikazio bidea eta ikasle izango dituen HH 4ko edo LH 2koaren komunikazio bidea. Baina hizkuntzaz eta hizkuntz komunikazioaz ari garenez, geure burua ezagututa, ikasleak ezagutzen saiatuko gara.

-   Sarrera Hizkuntza politikaren garrantzia Europako testuinguruan

-   HIIEEEM-ren Historia: Nola sortu zen, zein helburu dituen eta nola erabil daitekeen

-   Hizkuntza mailak

-   Baliabideen gaineko hausnarketa

### Zereginak

-   HEEEB mailen analisia:\
    Ikasleek, banaka edo bikoteetan, HEEEB maila bat aukeratu eta horri buruzko poster bat sortuko dute.
-   Norberaren HPE:\
    Ikasleek beraien HPE propioa sortuko dute, hizkuntza ikaskuntza ibilbidea eta hizkuntza gaitasunak islatuz. [Etxerako lana]{style="color: darkred"}
