# Eskolan hizkuntzen tratamendua: Ikastetxeko Hizkuntza Proiektua eta Hizkuntza Indartzeko Programako Irakaslea (HIPI)

Baliabideak: [@bikandiProyectoLinguisticoCentro1997; @ruizbikandiBigarrenHizkuntzarenDidaktika2010; @euskalherrikoikastolenkonfederazioaIkastolenHizkuntzProiektua2009]

Eskolan hizkuntzen tratamendua ikertzean, bi elementu garrantzitsu azpimarratu behar dira: Ikastetxeko Hizkuntza Proiektua eta Hizkuntza Indartzeko Programako Irakaslea (HIPI). Lehenengoak, Ikastetxeko Hizkuntza Proiektuak, ikastetxe bakoitzaren hizkuntza politika eta estrategia zehatza definitzen du. Hau da, nola antolatu eta kudeatu hizkuntzak eskolan, zein hizkuntza erabiliko den komunikazioan, irakaskuntzan, ikaskuntzan eta ebaluazioan, eta nola sustatuko den hizkuntza aniztasuna eta elebitasuna. Bestalde, HIPI figura da hizkuntza proiektu hori errealitate bihurtzeko ardatz nagusia. HIPIren rola ez da bakarrik hizkuntzaren didaktika, baizik eta ikastetxe osoan hizkuntza politikaren garapenean laguntzea, hizkuntzak modu integratuan eta koherentean tratatzeko. Bi elementu hauek, eskolan hizkuntzen tratamendu eraginkorra lortzeko funtsezkoak dira.

## Sarrera

Eskolan hizkuntzen tratamendua ez da soilik ikasleek hizkuntza bat edo beste bat ikastea. Ikastetxe bakoitzak autonomia du hizkuntza politika zehatza garatzeko, eta horrek eragin handia du ikasleen hizkuntza ikaskuntzan. Hizkuntzen tratamenduaren garrantzia ez da soilik ikasleen hizkuntza konpetentziak garatzean; gizarte anitz, kultura anitzeko eta hizkuntza anitzeko gizarte batean bizi garenez, garrantzitsua da ikasleek hizkuntza aniztasuna ulertzeko eta balioesteko gaitasuna ere garatzea.

## Egitura

-   Ikastetxeko Hizkuntza Proiektuaren Sarrera

-   Hizkuntza Indartzeko Programako Irakasleen Rola

-   Hizkuntzen Tratamenduaren Erronkak
