# Immigrazio hizkuntzen trataera

📹

<!-- -   [ ] Topa hezkuntzako webgunian -->

<!-- -   [ ] Topa adibidiak -->

<!-- -   [ ] Topa... -->

Aipatu arren, curriculum diseinutik aparte geratzen diren hainbat hizkuntza "ez-curricular" ere bada. Horrekin zer gertatzen den, arauak zer dioen, zein toki izan lezakeen eta zein ematen zaion eskolan eta gizartean. Zalantzoi nolabaiteko erantzunak emateko eskatuko zaie proiektuko hirugarren astean. Horretarako Hezkuntza Saileko zenbait weborri eta dokumentu bi erabiliko dira, aurreko klaseetako dokumentuez eta apunteez gain.

-   Immigrazio hizkuntzak eta ikastetxeak\
    Emigrazioko doluetan bigarrena hizkuntza @achoteguiloizateDuelosMigracionAproximacion2000\
    @hezkuntzasailaEleaniztasunaZer2017\
    @hezkuntzasailaEAEkoHezkuntzaSistema2019\
    @larreaHizkuntzaEtorkinakAzterketa2013\
    @europakokontseiluaHizkuntzenEuropakoErreferentzia2022

------------------------------------------------------------------------

Hizkuntzen Europako Erreferentzi Marko Bateratuaren liburu osagarria 202aan argitaratu zen, 2022an euskarazko bertsioa zabaldu zen [@europakokontseiluaHizkuntzenEuropakoErreferentzia2022]. Horretan *Gaitasun Eleaniztuna eta Kulturaniztuna* zehaztu ziren norbanakoaren aniztasun kultural eta linguistikoaren aberasgarri.

Ikuspegi eleaniztunak...

> ...gizabanakoak hizkuntza baten kultur ingurunean duen hizkuntz esperientzia zabaldu ahala, hasi familia-hizkuntzatik eta gizarte-hizkuntzaraino, oro har, eta beste herri batzuetako hizkuntzetaraino gero (izan eskolan edo unibertsitatean ikasiak, edo zuzeneko esperientziaren bidez ikasiak), hizkuntza horiek eta kultura horiek ez ditu adimeneko gune berezietan gordetzen; aldiz, komunikazio-gaitasun bat garatzen du, hizkuntz arloko ezagutza eta esperientzia guztien bidez eta hizkuntzen arteko harremanaren eta elkarreraginaren bidez. (EEMB, 2001, 1.3 atala)
>
> -- @europakokontseiluaHizkuntzenIkaskuntzaIrakaskuntza2005

![Gaitasun eleaniztuna eta kulturaniztuna \[\@europakokontseiluaHizkuntzenEuropakoErreferentzia2022\]](images/clipboard-525234506.png)

## Familia hizkuntzak, immigrazio hizkuntzak eta Hezkuntzaz

### Baskongadetako legeak

### Zer bihurtzen den

-   Euskal AEko 16 urte eta gehiagoko biztanle atzerritarrak, nazionalitate kontinentearen eta jardueraren arabera, lurralde historikoari eta sexuari jarraiki. 2022/01/01 [\*](https://eu.eustat.eus/elementos/ele0013700/euskal-aeko-16-urte-eta-gehiagoko-biztanle-atzerritarrak-nazionalitate-kontinentearen-eta-jardueraren-arabera-lurralde-historikoari-eta-sexuari-jarraiki/tbl0013791_e.html)

Hezkuntzako webgunean:

-   EAEko hezkuntza sistema. [Familientzako informazioa](EAEko hezkuntza sistema. Familientzako informazioa)
