# Aurretikoak {.unnumbered}

Ikasturte honetarako apunteak eguneratzen ari naiz; beraz, izan kontuan aldaketak egingo direla apunteotan ikastaroan zehar.

Informazio legal, ofizial eta abar: [Fakultateko webgunean](https://www.ehu.eus/eu/web/bilboko-hezkuntza-fakultatea/graduak/lehen-hezkuntza).

## Gaiak eta denboralizazio proposamena

Grebak, interesak, premiak eta abar tarteko, ikusteko dago ea zenbatean segitzen diogun hurrengo astez asteko proposamenari:

0.  Aurkezpena eta sarrera
    -   Zer den eta litzatekeen curriculuma [\*](../diapoak/00-Aurkezpena-24.html) `(1)`
1.  Hezkuntza ingurua, hizkuntzen agerrera eta curriculuma
    -   Europako Erreferentzi Markoa: Hizkuntzen Ikaskuntza Irakaskuntza eta Ebaluaziorako Europako Erreferentzia Markoa `(2)`
    -   Immigrazio hizkuntzen trataera `(barria)`
    -   IKTak eta hizkuntza `(9 eta 10)`
2.  Ikastetxeko hizkuntzen antolakuntza
    -   Gaitasunak eta hezkuntza sistema – Hizkuntza-komunikaziorako gaitasuna `(3)`
    -   Euskal hezkuntza sistemako eleaniztasuna: Diglosiatik elebitasunera eta handik eleaniztasunera `(4)`
    -   Hizkuntzen Trataera bateratua (HTB) `(6)`  
    [Aste honetan lehenengo mintegia]{style="color: darkred"}
    -   Hizkuntzak eta Edukiak Batera Ikastea (HEBI) *CLIL* `(7)`
3.  Gelako praktikaren antolakuntza eta hizkuntza
    -   Hizkuntzen irakaskuntzarako metodologien bilakaera `(12 a)`
    -   Irakaskuntzarako Diseinu Unibertsala (IDU) eta hizkuntza `(barria)`
    -   Proiektuak, atazak eta hizkuntza `(12 b)`  
    [Aste honetan bigarren mintegia]{style="color: darkred"}
    -   Interakzionismo-soziodiskursiboaren ikuskera. Testua ikasgunea.
    -   Sekuentzia Didaktikoak `(12 c + barri)`
    -   Hizkuntzan akatsak. Lapsusak, erroreak `(11)`

### Mintegietan

Mintegiak ebaluaziorako erabiliko dira.

1.  Lehenengo proiektuko bideoak

2. Role Playing

## Kontaktua, tutoretzak eta abar

Emaila

:   **juan**\[dot\]**abasolo**\[at\]**ehu**\[dot\]**eus**

Telegram

:   \@JuanAbasolo

Bulegoa

:   3S40B

Telefonoa

:   (+34) 94 601 **7567**

Tutoretzak

:   <http://labur.eus/JAbasolo-tutoretzak>
