# Portfoliorako oharrak

Portfoliak sarrera eta hiru atal izango ditu[\*](../diapoak/2025-Azken_klasea.html).

Sarreran egingo da ikasgaiaren balorazio orokorra eta ikasleak zehaztuko du bere lanbiderako zein ikaskuntza eskuratu duen zein lan eginaz.

Atalak izango dira ikasgaian "gai" moduan aipatuak:

1.  Hezkuntza ingurua, hizkuntzen agerrera eta curriculuma
2.  Ikastetxearen antolakuntza, ikaskuntzak eta hizkuntzen ikaskuntza
3.  Gelako praktikaren antolakuntza eta hizkuntza

Atal bakoitzak izango du bere sarrera, lanen zerrenda eta lanen azalpen pedagogikoa

Segidan lanak ordenan aurkeztuko dira honela:

-   Lanaren aurkezpena (paragrafo bat gehienez)

-   Lana bera

-   Lanaren balorazioa (paragrafo bat gehienez)

Hemendik aurrera, gairik gai, atalik atal lanen zerrenda, portfolioak gorde beharreko egitura.

------------------------------------------------------------------------

## Hezkuntza ingurua, hizkuntzen agerrera eta curriculuma

-   Bideo sorta

### Curriculumaz

-   Komunikazioa eta hezkuntza egungo curriculum dekretuan

### EEMB eta Hizkuntzen Portfolio Europarra

-   EEMB mailak.\
    Analisia eta hezkuntza jarduerarekiko loturak

-   Norberaren HPE: Ikasleek beraien HPE propioa sortuko dute, hizkuntza ikaskuntza ibilbidea eta hizkuntza gaitasunak islatuz.

### Hizkuntza ez‐curricularren trataera

-   Claustroaren aurrean irakurri beharreko dokumentua\
    Ariketa horrek tarte bi izan ditu askoren kasuan. Banakako idazketaren aurretik, talde hausnarketa egin bada, sarreran kontuan izan. Bestela zuzenean bakarka idatziari egin kasu.

### IKT hizkuntzaren erabilera eta hizkuntz paisaia

-   Berbako diskurtso idatzia\
    IKTen erabilera bideratu beharraz.

-   Idatziaren azterketa eta analisia\
    IDATapp edo IDATshboard erabilita aurrez idatzitakoen azterketa.

-   Webguneen zerrendaren sailkapena. Zuon ekarpenen atala erakutsi

## Ikastetxearen antolakuntza, ikaskuntzak eta hizkuntzen ikaskuntza

-   Role playingak

### Hezkuntzaren lau zutabeak eta gaitasun giltzarriak hizkuntzen didaktikan

-   Konpetentzien ikuskeraren alderaketa

-   Egoera komunikatiboa (A)

### Euskal Hezkuntza Sistemako Eleaniztasuna

-   Egoera komunikatiboa (B)

### Hizkuntzen Trataera Bateratuaz

-   Hizkuntzen arteko elementu eta gaitasun transferigarriak

-   Egoera komunikatiboa (C)

### Hizkuntzak eta Edukiak Batera Ikastea

-   HDIB zein ikasgai zein mailatan, zergatik

-   Egoera komunikatiboa (D)

## Gelako praktikaren antolakuntza eta hizkuntza

-   ~~Sekuentzia Didaktikoaren proposamena~~ ⏭️

### Hizkuntzen irakaskuntzarako metodologien bilakaera

-   ⏭️

### Ikaskuntzarako Diseinu Unibertsala eta hizkuntza

-   Praktiketako azalpen eta balorazioa\
    Ralabate eta Nelson (2017) liburuko kapitulu baten argitara

### Testua i(ra)kasgunea

-   Bost ekintza komunikatibo\
    Zu barne hartzen zaituenak irakaskuntzako subjektu legez, osagarriak aztertuta.

-   Ahozko testuaren moldaketak\
    Testu-arkitekturaren elementuak espreski aldatuta

### Lapsusak, huts egiteak eta erroreak

-   Testu idatzien azterketa\
    Erroreak identifikatu, sailkatu eta horietan oinarrituta, irakasleak ikaslearekin egin beharrekoaren proposamen justifikatua. Hiru testu, bata euskaraz, beste bat gaztelaniaz eta bat aukeran (ingelesa ere aukeragai dago, zure gaitasunaren arabera). Taldekideek ez testurik errepikatu barik.
